name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild -workspace 'Cities.xcworkspace' -scheme 'Cities' -destination 'platform=iOS Simulator,name=iPhone 8' test | xcpretty
    - name: Run a multi-line script
      run: xcodebuild -workspace 'Cities.xcworkspace' -scheme 'Cities' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO | xcpretty
